### ISSUE TITLE
Remove "JAGS" models

### ISSUE THREAD

**Issue by DBecker7** [DASL-Lab/provoc#1]
Ensure that nothing in [provoc_jags](https://github.com/DASL-Lab/provoc/blob/main/R/provoc_jags.R) is useful elsewhere, then delete.

There's no longer a need for the [`method = "jags"`](https://github.com/DASL-Lab/provoc/blob/08733909d1eb2821df081a3221278eed2e14af5c/R/provoc.R#L31) option in this package. The main `provoc` function can be purely the "`optim`" option.

**Comment by JeremyFaria** [comment]
Firstly, I will make a new branch for this issue. In that branch I will first ensure that none of the functions in provoc_jags are referenced anywhere else in the project. If a function is referenced I will take the appropiate measure in removing it, while maintaining that the function i'm removing it from still has the same functionality. I will commit every change I make to ensure I am making atomic commits. Once I ensured that nothin in provoc_jags is useful anywhere else I will delete the file. 

Secondly I will check the files to change any functions with a method = jags option, by taking appropiate measures in removing that option for functions without changing the functionality of the function. This would include removing paths where JAGS and runjags are required. 

Once all changes are committed I will merge the branch back to the main branch
