### ISSUE TITLE
Implement `predict.provoc` method

### ISSUE THREAD

**Issue by DBecker7** [DASL-Lab/provoc#13]
Function should take in a named list (`provoc` class) including an estimate of the proportions and the associated variant matrix, do the matrix multiplication, and return the results in the same order as the original data.

**Comment by danerkestey** [comment]
I will review the `provoc` class structure and implement the `predict.provoc` method to perform matrix multiplication using the provided proportions and variant matrix. I'll ensure the function returns results in the same order as the original data and align with the existing class methods.
