### ISSUE TITLE
Documentation inheritance

### ISSUE THREAD

**Issue by DBecker7** [DASL-Lab/provoc#15]
The variant matrix and mutation names params are repeated in multiple places. This is unnecessary. Check the [roxygen](https://roxygen2.r-lib.org/articles/reuse.html) documentation for re-using documentation.

**Comment by danerkestey** [comment]
I'll investigate how we are currently documenting, and implement Roxygen docs where nessesary

**Comment by DBecker7** [comment]
This was a nice-to-have that might have sped things up. Closing as wontfix.
